# 04 模型訓練

| | 內容 |
|---|---|
| 輸入 | `data/processed/`（01、03 的輸出） |
| 輸出 | `output/backtest/<時間>_notebook_04_tuning/`（逐窗分數、逐日 6 目標、432 點曲線 `curves.csv`，供 05 讀取）、`output/reports/04_runtimes.json` |

**現行模型**：
- 時刻（佔總分約 93%）：條件經驗分布（日別 × 夏月 × 星期 × 氣溫 2 箱）+ 學習式 LightGBM 在 PMF 層級修正 + 貝氏決策
- 量值：LightGBM 分位數迴歸（τ = 0.625 / 0.70 / 0.50）
- 氣象：五都 4 個溫度項；歷史用 CODiS 觀測，目標日用逐起點校正的 Accuweather
- 太陽光電：Windy 預測發電量 `pv_14`、`pv_sum`
- 6 目標 → 合成 432 點曲線

**回測設計**（`src/evaluation/backtest.py`）：每個窗從起點日 T 的次日 00:00 起算，負載截止於 T 23:50，
預測 3 天共 432 期；目標日的氣象只用預報（honest 模式）。調參組涵蓋全部資料，共 168 窗：
60 個全年起點、2025 與 2026 年 9 月下旬到 10 月上旬的 30 個同季節起點、2026-06-30～09-27 每天一個起點，重複的只算一次。

observed 模式（目標日也用觀測，樂觀）只作對照，可由 `python main.py evaluate --weather-mode observed` 重現。

調參組回測約 35 分鐘。

In [1]:
import sys
from pathlib import Path

ROOT = Path.cwd().resolve()
while not (ROOT / "config").is_dir():   # 找到專案根目錄（notebook 可從任何位置執行）
    ROOT = ROOT.parent
sys.path.insert(0, str(ROOT))

import os
import polars as pl
from src.logging_setup import setup_logging

os.chdir(ROOT)
setup_logging(stage="notebook_04", level="WARNING")
pl.Config.set_tbl_rows(60)
pl.Config.set_tbl_cols(30)
pl.Config.set_fmt_str_lengths(60)

polars.config.Config

In [2]:
import datetime as dt
import json
import time

from config import paths, settings
from src import workflow
from src.data import checks
from src.evaluation import backtest

runtimes = {}

## 1. 調參組回測（168 窗）

In [3]:
start = time.perf_counter()
run_dir = backtest.run("tuning", "notebook_04")
runtimes["backtest_tuning"] = round(time.perf_counter() - start, 1)
summary = json.loads((run_dir / "summary.json").read_text(encoding="utf-8"))
paths.REPORTS_DIR.mkdir(parents=True, exist_ok=True)
{k: summary[k] for k in ("n_windows", "skipped", "manifest_sha256", "data_matches_manifest", "runtime_seconds")}

2026-10-01 15:50:48 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 15:50:49 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 15:50:51 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 15:50:57 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 15:51:00 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 15:51:03 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 15:51:12 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 15:51:15 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 15:51:18 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 15:51:26 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 15:51:29 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 15:51:32 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 15:51:41 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 15:51:44 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 15:51:48 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 15:51:57 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 15:52:00 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 15:52:03 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 15:52:12 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 15:52:15 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 15:52:18 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 15:52:27 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 15:52:31 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 15:52:34 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 15:52:43 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 15:52:46 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 15:52:49 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 15:52:59 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 15:53:02 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 15:53:06 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 15:53:15 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 15:53:18 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 15:53:22 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 15:53:32 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 15:53:35 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 15:53:38 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 15:53:48 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 15:53:51 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 15:53:55 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 15:54:04 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 15:54:08 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 15:54:11 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 15:54:21 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 15:54:25 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 15:54:28 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 15:54:38 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 15:54:42 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 15:54:46 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 15:54:57 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 15:55:01 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 15:55:05 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 15:55:18 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 15:55:22 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 15:55:26 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 15:55:39 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 15:55:43 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 15:55:48 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 15:56:01 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 15:56:05 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 15:56:09 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 15:56:22 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 15:56:26 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 15:56:30 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 15:56:44 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 15:56:48 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 15:56:52 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 15:57:06 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 15:57:10 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 15:57:14 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 15:57:28 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 15:57:32 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 15:57:36 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 15:57:49 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 15:57:53 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 15:57:57 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 15:58:11 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 15:58:15 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 15:58:19 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 15:58:33 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 15:58:38 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 15:58:42 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 15:58:55 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 15:59:00 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 15:59:04 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 15:59:18 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 15:59:23 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 15:59:27 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 15:59:41 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 15:59:45 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 15:59:49 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:00:04 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:00:08 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:00:12 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:00:26 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:00:30 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:00:34 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:00:49 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:00:53 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:00:57 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:01:11 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:01:16 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:01:20 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:01:34 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:01:39 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:01:43 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:01:57 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:02:02 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:02:06 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:02:20 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:02:25 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:02:29 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:02:44 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:02:48 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:02:52 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:03:07 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:03:11 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:03:15 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:03:30 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:03:34 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:03:39 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:03:53 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:03:58 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:04:03 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:04:17 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:04:22 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:04:26 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:04:41 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:04:45 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:04:50 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:05:04 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:05:08 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:05:13 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:05:28 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:05:32 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:05:37 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:05:52 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:05:57 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:06:01 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:06:16 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:06:21 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:06:26 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:06:41 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:06:45 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:06:50 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:07:05 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:07:10 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:07:14 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:07:29 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:07:34 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:07:38 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:07:53 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:07:57 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:08:02 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:08:18 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:08:23 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:08:27 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:08:43 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:08:48 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:08:53 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:09:09 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:09:14 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:09:18 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:09:36 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:09:40 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:09:45 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:10:02 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:10:07 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:10:12 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:10:29 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:10:34 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:10:39 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:10:56 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:11:01 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:11:06 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:11:24 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:11:29 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:11:34 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:11:51 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:11:57 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:12:02 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:12:20 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:12:25 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:12:29 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:12:47 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:12:52 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:12:57 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:13:16 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:13:21 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:13:26 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:13:44 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:13:49 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:13:54 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:14:04 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:14:07 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:14:09 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:14:18 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:14:20 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:14:23 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:14:31 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:14:34 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:14:36 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:14:45 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:14:47 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:14:50 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:14:58 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:15:01 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:15:03 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:15:12 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:15:14 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:15:16 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:15:25 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:15:27 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:15:30 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:15:38 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:15:41 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:15:43 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:15:52 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:15:55 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:15:57 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:16:06 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:16:09 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:16:11 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:16:20 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:16:23 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:16:25 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:16:34 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:16:37 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:16:39 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:16:48 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:16:51 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:16:53 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:17:02 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:17:05 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:17:07 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:17:17 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:17:19 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:17:22 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:17:31 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:17:34 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:17:36 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:17:46 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:17:48 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:17:51 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:18:00 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:18:02 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:18:05 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:18:14 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:18:17 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:18:19 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:18:29 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:18:31 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:18:34 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:18:43 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:18:45 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:18:48 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:18:57 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:19:00 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:19:02 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:19:11 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:19:14 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:19:16 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:19:26 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:19:28 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:19:31 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:19:40 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:19:43 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:19:45 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:19:55 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:19:58 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:20:00 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:20:10 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:20:12 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:20:15 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:20:24 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:20:27 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:20:29 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:20:39 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:20:41 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:20:44 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:20:53 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:20:55 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:20:58 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:21:07 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:21:10 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:21:12 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:21:22 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:21:24 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:21:27 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:21:36 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:21:39 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:21:41 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:21:50 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:21:53 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:21:55 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:22:04 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:22:08 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:22:11 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:22:25 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:22:29 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:22:33 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:22:45 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:22:48 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:22:50 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:22:59 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:23:02 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:23:04 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:23:14 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:23:16 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:23:19 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:23:34 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:23:37 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:23:41 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:23:56 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:24:00 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:24:04 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:24:19 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:24:21 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:24:24 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:24:34 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:24:36 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:24:39 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:24:48 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:24:50 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:24:53 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:25:02 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:25:05 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:25:07 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:25:16 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:25:18 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:25:21 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:25:30 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:25:32 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:25:35 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:25:44 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:25:46 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:25:49 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:25:57 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:26:00 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:26:02 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:26:11 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:26:14 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:26:16 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:26:25 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:26:27 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:26:30 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:26:39 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:26:41 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:26:44 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:26:53 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:26:55 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:26:58 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:27:07 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:27:09 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:27:12 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:27:21 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:27:23 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:27:26 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:27:35 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:27:37 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:27:40 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:27:49 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:27:51 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:27:53 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:28:02 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:28:05 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:28:07 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:28:16 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:28:19 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:28:21 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:28:30 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:28:33 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:28:35 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:28:44 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:28:47 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:28:49 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:28:58 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:29:00 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:29:03 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:29:12 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:29:15 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:29:17 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:29:26 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:29:29 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:29:31 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:29:40 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:29:43 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:29:45 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:29:54 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:29:57 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:29:59 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:30:08 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:30:11 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:30:13 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:30:22 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:30:25 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:30:27 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:30:37 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:30:39 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:30:41 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:30:51 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:30:53 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:30:56 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:31:05 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:31:07 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:31:10 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:31:19 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:31:21 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:31:24 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:31:33 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:31:36 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:31:38 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:31:48 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:31:51 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:31:53 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:32:03 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:32:05 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:32:08 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:32:17 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:32:20 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:32:22 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:32:32 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:32:35 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:32:37 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:32:47 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:32:50 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:32:52 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:33:02 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:33:05 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:33:07 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:33:17 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:33:19 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:33:22 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:33:32 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:33:34 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:33:37 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:33:46 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:33:49 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:33:51 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:34:01 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:34:04 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:34:06 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:34:16 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:34:18 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:34:21 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:34:31 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:34:34 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:34:36 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:34:46 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:34:48 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:34:51 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:35:00 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:35:03 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:35:05 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:35:15 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:35:18 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:35:20 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:35:30 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:35:32 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:35:35 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:35:45 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:35:47 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:35:50 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:35:59 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:36:02 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:36:05 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:36:17 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:36:20 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:36:22 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:36:32 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:36:34 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:36:37 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:36:47 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:36:49 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:36:52 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:37:07 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:37:11 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:37:15 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:37:30 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:37:34 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:37:37 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:37:53 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:37:57 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:38:01 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:38:14 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:38:18 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:38:21 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:38:36 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:38:40 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:38:43 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:39:01 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:39:04 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:39:07 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:39:21 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:39:24 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:39:28 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:39:44 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:39:48 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:39:53 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:40:09 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:40:13 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:40:17 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:40:34 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:40:39 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:40:43 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:40:59 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:41:03 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:41:07 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:41:11 | WARNING  | src.workflow | total_score = 0.86197（標準誤 0.04311），最壞折 2.77443（2025-08-01）［氣象模式 honest］
shape: (5, 5)
┌─────────────────┬──────────┬────────┬──────────────┬──────────┐
│ component       ┆ raw      ┆ weight ┆ contribution ┆ share    │
│ ---             ┆ ---      ┆ ---    ┆ ---          ┆ ---      │
│ str             ┆ f64      ┆ f64    ┆ f64          ┆ f64      │
╞═════════════════╪══════════╪════════╪══════════════╪══════════╡
│ s_peak_time     ┆ 5.297886 ┆ 0.15   ┆ 0.794683     ┆ 0.921934 │
│ s_ramp_up       ┆ 0.159252 ┆ 0.15   ┆ 0.023888     ┆ 0.027713 │
│ s_under_penalty ┆ 0.014722 ┆ 1.0    ┆ 0.014722     ┆ 0.017079 │
│ s_ramp_down     ┆ 0.145434 ┆ 0.1    ┆ 0.014543     ┆ 0.016872 │
│ s_peak_mw       ┆ 0.023563 ┆ 0.6    ┆ 0.014138     ┆ 0.016402 │
└─────────────────┴──────────┴────────┴──────────────┴──────────┘

2026-10-01 16:41:11 | WARNING  | src.evaluation.backtest | 回測 [notebook_04／tuning] 168 窗：total_score 0.86197（標準誤 0.04311），同季節 0.66723 → 20261001_155046_notebook_04_tuning

{'n_windows': 168,
 'skipped': [],
 'manifest_sha256': 'ef72d579a4e538d7599be17f778a60dc6d2eb64f0ad6705267b68be07d77f1ef',
 'data_matches_manifest': True,
 'runtime_seconds': 3027.8}

In [4]:
pl.DataFrame([{"範圍": "全體", **summary["overall"]}]
             + [{"範圍": name, **value} for name, value in summary["subsets"].items()])

shape: (6, 11)
┌─────────┬─────┬─────────┬─────────┬────────┬────────┬────────┬────────┬────────┬────────┬────────┐
│ 範圍    ┆ n   ┆ total_s ┆ stderr  ┆ worst  ┆ worst_ ┆ s_peak ┆ s_peak ┆ s_ramp ┆ s_ramp ┆ s_unde │
│ ---     ┆ --- ┆ core    ┆ ---     ┆ ---    ┆ origin ┆ _mw    ┆ _time  ┆ _up    ┆ _down  ┆ r_pena │
│ str     ┆ i64 ┆ ---     ┆ f64     ┆ f64    ┆ ---    ┆ ---    ┆ ---    ┆ ---    ┆ ---    ┆ lty    │
│         ┆     ┆ f64     ┆         ┆        ┆ str    ┆ f64    ┆ f64    ┆ f64    ┆ f64    ┆ ---    │
│         ┆     ┆         ┆         ┆        ┆        ┆        ┆        ┆        ┆        ┆ f64    │
╞═════════╪═════╪═════════╪═════════╪════════╪════════╪════════╪════════╪════════╪════════╪════════╡
│ 全體    ┆ 168 ┆ 0.86197 ┆ 0.04311 ┆ 2.7744 ┆ 2025-0 ┆ 0.0235 ┆ 5.2978 ┆ 0.1592 ┆ 0.1454 ┆ 0.0147 │
│         ┆     ┆ 4       ┆ 4       ┆ 26     ┆ 8-01   ┆ 63     ┆ 86     ┆ 52     ┆ 34     ┆ 22     │
│ 同季節  ┆ 30  ┆ 0.66722 ┆ 0.06398 ┆ 1.7778 ┆ 2025-0 ┆ 0.0228 ┆ 4.0230 ┆ 0.1560 ┆ 0.1439 ┆ 0.0122 │
│         ┆     ┆ 9       ┆ 8       ┆ 65     ┆ 9-20   ┆ 82     ┆ 56     ┆ 88     ┆ 75     ┆ 31     │
│ 週四五  ┆ 24  ┆ 0.87098 ┆ 0.11938 ┆ 2.3785 ┆ 2025-0 ┆ 0.0240 ┆ 5.3732 ┆ 0.1612 ┆ 0.1369 ┆ 0.0127 │
│ 六      ┆     ┆ 8       ┆ 8       ┆ 6      ┆ 6-11   ┆ 16     ┆ 26     ┆ 15     ┆ 9      ┆ 14     │
│ 含週六  ┆ 74  ┆ 0.97521 ┆ 0.06481 ┆ 2.7744 ┆ 2025-0 ┆ 0.0229 ┆ 6.0209 ┆ 0.1898 ┆ 0.1517 ┆ 0.0146 │
│         ┆     ┆ 5       ┆ 8       ┆ 26     ┆ 8-01   ┆ 45     ┆ 92     ┆ 84     ┆ 72     ┆ 4      │
│ 夏月末  ┆ 18  ┆ 0.55494 ┆ 0.04663 ┆ 0.8881 ┆ 2025-0 ┆ 0.0227 ┆ 3.2587 ┆ 0.1964 ┆ 0.1639 ┆ 0.0065 │
│ 期      ┆     ┆         ┆ 1       ┆ 08     ┆ 9-27   ┆ 99     ┆ 55     ┆ 15     ┆ 04     ┆ 94     │
│ 含連假  ┆ 37  ┆ 0.91319 ┆ 0.07899 ┆ 1.9588 ┆ 2026-0 ┆ 0.0295 ┆ 5.5456 ┆ 0.2285 ┆ 0.1684 ┆ 0.0125 │
│ 或停班  ┆     ┆ 3       ┆ 3       ┆ 3      ┆ 6-19   ┆ 27     ┆ 14     ┆ 09     ┆ 9      ┆ 1      │
└─────────┴─────┴─────────┴─────────┴────────┴────────┴────────┴────────┴────────┴────────┴────────┘

## 2. 以鎖定設定重新訓練並預測提交日（資料截止日次日起 3 天）

與比賽當天 `run_submission.py` 第 5–6 步是同一個函式；下表是每天的 6 個量。

In [5]:
origin = checks.cutoff_date()
days = [origin + dt.timedelta(days=k) for k in range(1, settings.PREDICT_HORIZON_DAYS + 1)]
start = time.perf_counter()
curves, intended, requested = workflow.predict_days(origin, days)
runtimes["train_and_predict"] = round(time.perf_counter() - start, 1)
pl.DataFrame([
    {"日期": str(day), "p_day": t.p_day, "t_day": t.t_day, "p_night": t.p_night,
     "t_night": t.t_night, "ramp_up": t.ramp_up, "ramp_down": t.ramp_down}
    for day, t in intended.items()
])

2026-10-01 16:41:12 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:41:13 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:41:15 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:41:16 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:41:31 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:41:35 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-10-01 16:41:40 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

shape: (3, 7)
┌────────────┬──────────────┬───────┬──────────────┬─────────┬─────────────┬────────────┐
│ 日期       ┆ p_day        ┆ t_day ┆ p_night      ┆ t_night ┆ ramp_up     ┆ ramp_down  │
│ ---        ┆ ---          ┆ ---   ┆ ---          ┆ ---     ┆ ---         ┆ ---        │
│ str        ┆ f64          ┆ i64   ┆ f64          ┆ i64     ┆ f64         ┆ f64        │
╞════════════╪══════════════╪═══════╪══════════════╪═════════╪═════════════╪════════════╡
│ 2026-10-01 ┆ 39873.313879 ┆ 840   ┆ 36696.089961 ┆ 1030    ┆ 1413.066981 ┆ 673.009463 │
│ 2026-10-02 ┆ 37304.969475 ┆ 840   ┆ 35116.704445 ┆ 1050    ┆ 1321.752317 ┆ 678.189983 │
│ 2026-10-03 ┆ 32314.733346 ┆ 840   ┆ 32414.044778 ┆ 1090    ┆ 725.334866  ┆ 543.416035 │
└────────────┴──────────────┴───────┴──────────────┴─────────┴─────────────┴────────────┘

In [6]:
(paths.REPORTS_DIR / "04_runtimes.json").write_text(json.dumps(runtimes, indent=2), encoding="utf-8")
runtimes

{'backtest_tuning': 3027.8, 'train_and_predict': 32.6}

## 3. 開發期實驗總表（資料到 2026-06-30，78 窗）

開發期的調參組是 60 個全年起點加上 2025-09-19～10-09 的 21 個同季節起點，重複 3 個，共 78 窗。
每個實驗都走同一套回測（honest 模式），與當時的參考配對比較；當時學習式修正的權重是 0.5。
這些紀錄由 commit `ec3d9a0` 的程式與資料產生，切到該版本即可用同樣的指令重現。
**所有變體都在執行前決定**，看到結果後沒有追加或微調，以免對調參組過度配適。

選模門檻：全部調參窗的配對改善大於 1 個標準誤，且同季節子集沒有變差超過 1 個標準誤；
通過者再以另外 2 個種子確認。差值為正代表變差；「對照」是配對比較的參考紀錄。

In [7]:
EXPERIMENTS = {
    "current_best": "參考：含 UV、不含 Windy",
    "codis_lag1": "CODiS 只到起點前一天",
    "4a_A1_noUV": "氣象不含 UV（採用）",
    "4a_A1raw_noUV_uncal": "目標日預報不校正",
    "4a_B_forecast": "歷史也改用預報",
    "4a_N_noweather": "不用氣象",
    "4c_windy": "加入 Windy 太陽光電預測（採用）",
    "4e_E1_timing_seeds5": "時刻學習模型 5 種子平均",
    "4f_drop_zero_split": "刪除 6 個未使用的特徵（採用）",
    "4g_mix03": "時刻學習權重 0.3",
    "4g_mix07": "時刻學習權重 0.7",
    "4h_magnitude_seeds5": "量值模型 5 種子平均",
    "4d_recursive_ar": "對照：10 分鐘一步的遞迴 AR",
}
names = pl.DataFrame({"label": list(EXPERIMENTS), "實驗": list(EXPERIMENTS.values())})
experiments = names.join(backtest.experiment_table("2026*"), on="label", how="left")
experiments.select("實驗", "total_score", "同季節", "s_peak_time", "差值", "標準誤倍數",
                   "同季節差值", "通過門檻", "對照", "耗時秒")

shape: (13, 10)
┌─────────┬─────────┬─────────┬─────────┬─────────┬─────────┬─────────┬─────────┬─────────┬────────┐
│ 實驗    ┆ total_s ┆ 同季節  ┆ s_peak_ ┆ 差值    ┆ 標準誤  ┆ 同季節  ┆ 通過門  ┆ 對照    ┆ 耗時秒 │
│ ---     ┆ core    ┆ ---     ┆ time    ┆ ---     ┆ 倍數    ┆ 差值    ┆ 檻      ┆ ---     ┆ ---    │
│ str     ┆ ---     ┆ f64     ┆ ---     ┆ f64     ┆ ---     ┆ ---     ┆ ---     ┆ str     ┆ f64    │
│         ┆ f64     ┆         ┆ f64     ┆         ┆ f64     ┆ f64     ┆ bool    ┆         ┆        │
╞═════════╪═════════╪═════════╪═════════╪═════════╪═════════╪═════════╪═════════╪═════════╪════════╡
│ 參考：  ┆ 1.05629 ┆ 0.75880 ┆ 6.58006 ┆ null    ┆ null    ┆ null    ┆ null    ┆ null    ┆ 912.1  │
│ 含 UV、 ┆ 4       ┆ 8       ┆ 9       ┆         ┆         ┆         ┆         ┆         ┆        │
│ 不含    ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ Windy   ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ CODiS   ┆ 1.05935 ┆ 0.75971 ┆ 6.60064 ┆ 0.00306 ┆ 0.67262 ┆ 0.00090 ┆ false   ┆ 2026092 ┆ 1482.0 │
│ 只到起  ┆ 7       ┆ 7       ┆ 1       ┆ 3       ┆ 9       ┆ 9       ┆         ┆ 7_14200 ┆        │
│ 點前一  ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆ 0_curre ┆        │
│ 天      ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆ nt_best ┆        │
│         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆ _tuning ┆        │
│ 氣象不  ┆ 1.06447 ┆ 0.76073 ┆ 6.62996 ┆ 0.00818 ┆ 0.80785 ┆ 0.00193 ┆ false   ┆ 2026092 ┆ 1919.0 │
│ 含 UV（ ┆ 5       ┆ 8       ┆ 8       ┆ 1       ┆ 5       ┆         ┆         ┆ 7_14200 ┆        │
│ 採用）  ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆ 0_curre ┆        │
│         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆ nt_best ┆        │
│         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆ _tuning ┆        │
│ 目標日  ┆ 1.08094 ┆ 0.77772 ┆ 6.74490 ┆ 0.02465 ┆ 1.93774 ┆ 0.01891 ┆ false   ┆ 2026092 ┆ 1975.8 │
│ 預報不  ┆ 9       ┆ 2       ┆ 1       ┆ 5       ┆ 6       ┆ 4       ┆         ┆ 7_14200 ┆        │
│ 校正    ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆ 0_curre ┆        │
│         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆ nt_best ┆        │
│         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆ _tuning ┆        │
│ 歷史也  ┆ 1.07602 ┆ 0.76911 ┆ 6.71522 ┆ 0.01973 ┆ 1.58086 ┆ 0.01030 ┆ false   ┆ 2026092 ┆ 2793.4 │
│ 改用預  ┆ 9       ┆ 4       ┆ 1       ┆ 5       ┆ 4       ┆ 6       ┆         ┆ 7_14200 ┆        │
│ 報      ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆ 0_curre ┆        │
│         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆ nt_best ┆        │
│         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆ _tuning ┆        │
│ 不用氣  ┆ 1.08729 ┆ 0.79947 ┆ 6.77339 ┆ 0.03100 ┆ 1.91130 ┆ 0.04066 ┆ false   ┆ 2026092 ┆ 1852.5 │
│ 象      ┆ 5       ┆ 7       ┆ 2       ┆ 2       ┆ 1       ┆ 9       ┆         ┆ 7_14200 ┆        │
│         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆ 0_curre ┆        │
│         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆ nt_best ┆        │
│         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆ _tuning ┆        │
│ 加入    ┆ 1.04169 ┆ 0.76024 ┆ 6.48784 ┆ -0.0227 ┆ 1.81051 ┆ -0.0004 ┆ true    ┆ 2026092 ┆ 2097.8 │
│ Windy   ┆ 3       ┆ 6       ┆ 6       ┆ 81      ┆ 1       ┆ 91      ┆         ┆ 8_10130 ┆        │
│ 太陽光  ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆ 0_4a_A1 ┆        │
│ 電預測  ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆ _noUV_t ┆        │
│ （採用  ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆ uning   ┆        │
│ ）      ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ 時刻學  ┆ 1.05931 ┆ 0.77352 ┆ 6.60019 ┆ 0.00301 ┆ 0.62047 ┆ 0.01472 ┆ false   ┆ 2026092 ┆ 4314.5 │
│ 習模型  ┆ 2       ┆ 9       ┆         ┆ 8       ┆ 6       ┆ 1       ┆         ┆ 7_14200 ┆        │
│ 5 種子  ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆ 0_curre ┆        │
│ 平均    ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆ nt_best ┆        │
│         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆ _tuning ┆        │
│ 刪除 6  ┆ 1.06447 ┆ 0.76073 ┆ 6.62996 ┆ 0.0     ┆ inf     ┆ 0.0     ┆ false   ┆ 2026092 ┆ 2097.1 │
│ 個未使  ┆ 5       ┆ 8       ┆ 8       ┆         ┆         ┆         ┆         ┆ 8_10130 ┆        │
│ 用的特  ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆ 0_4a_A1 ┆        │
│ 徵（採  ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆ _noUV_t ┆        │
│ 用）    ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆ uning   ┆        │
│ 時刻學  ┆ 1.07946 ┆ 0.82645 ┆ 6.72975 ┆ 0.01498 ┆ 1.18992 ┆ 0.06572 ┆ false   ┆ 2026092 ┆ 2399.9 │
│ 習權重  ┆         ┆ 8       ┆         ┆ 5       ┆ 6       ┆ 1       ┆         ┆ 8_10130 ┆        │
│ 0.3     ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆ 0_4a_A1 ┆        │
│         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆ _noUV_t ┆        │
│         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆ uning   ┆        │
│ 時刻學  ┆ 1.06094 ┆ 0.70632 ┆ 6.60642 ┆ -0.0035 ┆ 0.22482 ┆ -0.0544 ┆ false   ┆ 2026092 ┆ 2391.9 │
│ 習權重  ┆ 3       ┆ 5       ┆ 2       ┆ 32      ┆ 4       ┆ 12      ┆         ┆ 8_10130 ┆        │
│ 0.7     ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆ 0_4a_A1 ┆        │
│         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆ _noUV_t ┆        │
│         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆ uning   ┆        │
│ 量值模  ┆ 1.06388 ┆ 0.75936 ┆ 6.62996 ┆ -0.0005 ┆ 1.52613 ┆ -0.0013 ┆ true    ┆ 2026092 ┆ 5095.2 │
│ 型 5    ┆ 4       ┆ 9       ┆ 8       ┆ 9       ┆ 6       ┆ 69      ┆         ┆ 8_10130 ┆        │
│ 種子平  ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆ 0_4a_A1 ┆        │
│ 均      ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆ _noUV_t ┆        │
│         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆ uning   ┆        │
│ 對照：1 ┆ 1.90909 ┆ 0.88830 ┆ 11.6666 ┆ 0.84462 ┆ 7.75091 ┆ 0.12757 ┆ false   ┆ 2026092 ┆ 37.0   │
│ 0 分鐘  ┆ 4       ┆ 9       ┆ 61      ┆         ┆ 2       ┆ 2       ┆         ┆ 8_10130 ┆        │
│ 一步的  ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆ 0_4a_A1 ┆        │
│ 遞迴 AR ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆ _noUV_t ┆        │
│         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆ uning   ┆        │
└─────────┴─────────┴─────────┴─────────┴─────────┴─────────┴─────────┴─────────┴─────────┴────────┘

In [8]:
experiments.select("實驗", "label", "覆寫")

shape: (13, 3)
┌─────────────────────────────────┬─────────────────────┬──────────────────────────────────────────┐
│ 實驗                            ┆ label               ┆ 覆寫                                     │
│ ---                             ┆ ---                 ┆ ---                                      │
│ str                             ┆ str                 ┆ str                                      │
╞═════════════════════════════════╪═════════════════════╪══════════════════════════════════════════╡
│ 參考：含 UV、不含 Windy         ┆ current_best        ┆ {}                                       │
│ CODiS 只到起點前一天            ┆ codis_lag1          ┆ {}                                       │
│ 氣象不含 UV（採用）             ┆ 4a_A1_noUV          ┆ {"WEATHER_METRICS": ["day_tmax",         │
│                                 ┆                     ┆ "day_tmin", "night_tmax", "…             │
│ 目標日預報不校正                ┆ 4a_A1raw_noUV_uncal ┆ {"WEATHER_METRICS": ["day_tmax",         │
│                                 ┆                     ┆ "day_tmin", "night_tmax", "…             │
│ 歷史也改用預報                  ┆ 4a_B_forecast       ┆ {}                                       │
│ 不用氣象                        ┆ 4a_N_noweather      ┆ {"ENABLE_TIER1_WEATHER": false,          │
│                                 ┆                     ┆ "TIMING_TEMPERATURE_BINS": 1…            │
│ 加入 Windy 太陽光電預測（採用） ┆ 4c_windy            ┆ {"ENABLE_WINDY": true}                   │
│ 時刻學習模型 5 種子平均         ┆ 4e_E1_timing_seeds5 ┆ {"TIMING_LEARNED_N_SEEDS": 5}            │
│ 刪除 6 個未使用的特徵（採用）   ┆ 4f_drop_zero_split  ┆ {"EXCLUDED_FEATURES":                    │
│                                 ┆                     ┆ ["is_lunar_new_year_eve", "night_price…  │
│ 時刻學習權重 0.3                ┆ 4g_mix03            ┆ {"TIMING_LEARNED_MIX": 0.3}              │
│ 時刻學習權重 0.7                ┆ 4g_mix07            ┆ {"TIMING_LEARNED_MIX": 0.7}              │
│ 量值模型 5 種子平均             ┆ 4h_magnitude_seeds5 ┆ {"MAGNITUDE_N_SEEDS": 5}                 │
│ 對照：10 分鐘一步的遞迴 AR      ┆ 4d_recursive_ar     ┆ {"MODEL_VARIANT": "recursive_ar"}        │
└─────────────────────────────────┴─────────────────────┴──────────────────────────────────────────┘

## 4. 以全部資料調參（168 窗）

取得到 2026-09-30 的負載後，只重新調時刻模型中由回測選出的 3 個參數，各試兩個值，在執行前就決定：
學習式修正權重 `TIMING_LEARNED_MIX`（0.5 → 0.3／0.7）、近期同星期分布在 `t_night` 的權重
（0.5 → 0.3／0.7）、`t_night` 的收縮強度（5 → 0／10）。門檻同上，通過者再以 2 個種子確認。

In [9]:
TUNING = {
    "full_mix03": "學習式修正權重 0.3",
    "full_mix07": "學習式修正權重 0.7（採用）",
    "full_recent03": "近期同星期權重 0.3",
    "full_recent07": "近期同星期權重 0.7",
    "full_alpha0": "t_night 收縮強度 0",
    "full_alpha10": "t_night 收縮強度 10",
}
tuning = pl.DataFrame({"label": list(TUNING), "變體": list(TUNING.values())}).join(
    backtest.experiment_table("20261001_*_full_*"), on="label", how="left")
tuning.select("變體", "窗數", "total_score", "同季節", "差值", "標準誤倍數", "同季節差值", "同季節標準誤倍數", "通過門檻")

shape: (6, 9)
┌───────────┬──────┬───────────┬──────────┬───────────┬───────────┬──────────┬──────────┬──────────┐
│ 變體      ┆ 窗數 ┆ total_sco ┆ 同季節   ┆ 差值      ┆ 標準誤倍  ┆ 同季節差 ┆ 同季節標 ┆ 通過門檻 │
│ ---       ┆ ---  ┆ re        ┆ ---      ┆ ---       ┆ 數        ┆ 值       ┆ 準誤倍數 ┆ ---      │
│ str       ┆ i64  ┆ ---       ┆ f64      ┆ f64       ┆ ---       ┆ ---      ┆ ---      ┆ bool     │
│           ┆      ┆ f64       ┆          ┆           ┆ f64       ┆ f64      ┆ f64      ┆          │
╞═══════════╪══════╪═══════════╪══════════╪═══════════╪═══════════╪══════════╪══════════╪══════════╡
│ 學習式修  ┆ 168  ┆ 0.899929  ┆ 0.772512 ┆ 0.027295  ┆ 3.092832  ┆ 0.054409 ┆ 3.662085 ┆ false    │
│ 正權重    ┆      ┆           ┆          ┆           ┆           ┆          ┆          ┆          │
│ 0.3       ┆      ┆           ┆          ┆           ┆           ┆          ┆          ┆          │
│ 學習式修  ┆ 168  ┆ 0.861974  ┆ 0.667229 ┆ -0.010661 ┆ 1.144921  ┆ -0.05087 ┆ 2.26406  ┆ true     │
│ 正權重    ┆      ┆           ┆          ┆           ┆           ┆ 3        ┆          ┆          │
│ 0.7（採用 ┆      ┆           ┆          ┆           ┆           ┆          ┆          ┆          │
│ ）        ┆      ┆           ┆          ┆           ┆           ┆          ┆          ┆          │
│ 近期同星  ┆ 168  ┆ 0.871949  ┆ 0.717555 ┆ -0.000686 ┆ 0.286544  ┆ -0.00054 ┆ 0.064757 ┆ false    │
│ 期權重    ┆      ┆           ┆          ┆           ┆           ┆ 7        ┆          ┆          │
│ 0.3       ┆      ┆           ┆          ┆           ┆           ┆          ┆          ┆          │
│ 近期同星  ┆ 168  ┆ 0.873716  ┆ 0.711559 ┆ 0.001082  ┆ 0.421747  ┆ -0.00654 ┆ 0.62695  ┆ false    │
│ 期權重    ┆      ┆           ┆          ┆           ┆           ┆ 4        ┆          ┆          │
│ 0.7       ┆      ┆           ┆          ┆           ┆           ┆          ┆          ┆          │
│ t_night   ┆ 168  ┆ 0.874609  ┆ 0.719357 ┆ 0.001974  ┆ 1.17889   ┆ 0.001254 ┆ 0.398919 ┆ false    │
│ 收縮強度  ┆      ┆           ┆          ┆           ┆           ┆          ┆          ┆          │
│ 0         ┆      ┆           ┆          ┆           ┆           ┆          ┆          ┆          │
│ t_night   ┆ 168  ┆ 0.872012  ┆ 0.718102 ┆ -0.000622 ┆ 0.885966  ┆ 0.0      ┆ inf      ┆ false    │
│ 收縮強度  ┆      ┆           ┆          ┆           ┆           ┆          ┆          ┆          │
│ 10        ┆      ┆           ┆          ┆           ┆           ┆          ┆          ┆          │
└───────────┴──────┴───────────┴──────────┴───────────┴───────────┴──────────┴──────────┴──────────┘

In [10]:
# 參考 full_ref 的設定與現行設定只差學習式修正權重（0.5）；三個種子都通過才採用 0.7
backtest.seed_confirmation_table([(42, "full_ref", "full_mix07"),
                                   (1337, "full_ref_seed1337", "full_mix07_seed1337"),
                                   (2718, "full_ref_seed2718", "full_mix07_seed2718")])

shape: (4, 8)
┌──────┬──────────┬──────────┬───────────┬────────────┬────────────┬──────────────────┬──────────┐
│ 種子 ┆ 參考     ┆ 候選     ┆ 差值      ┆ 標準誤倍數 ┆ 同季節差值 ┆ 同季節標準誤倍數 ┆ 通過門檻 │
│ ---  ┆ ---      ┆ ---      ┆ ---       ┆ ---        ┆ ---        ┆ ---              ┆ ---      │
│ str  ┆ f64      ┆ f64      ┆ f64       ┆ f64        ┆ f64        ┆ f64              ┆ bool     │
╞══════╪══════════╪══════════╪═══════════╪════════════╪════════════╪══════════════════╪══════════╡
│ 42   ┆ 0.872634 ┆ 0.861974 ┆ -0.010661 ┆ 1.144921   ┆ -0.050873  ┆ 2.26406          ┆ true     │
│ 1337 ┆ 0.865058 ┆ 0.853047 ┆ -0.012012 ┆ 1.269053   ┆ -0.054003  ┆ 2.738415         ┆ true     │
│ 2718 ┆ 0.86161  ┆ 0.85179  ┆ -0.00982  ┆ 1.076172   ┆ -0.038623  ┆ 2.104666         ┆ true     │
│ 平均 ┆ 0.866434 ┆ 0.855604 ┆ -0.010831 ┆ 1.21185    ┆ -0.047833  ┆ 2.461861         ┆ true     │
└──────┴──────────┴──────────┴───────────┴────────────┴────────────┴──────────────────┴──────────┘