# 04 模型訓練

| | 內容 |
|---|---|
| 輸入 | `data/processed/`（01、03 的輸出） |
| 輸出 | `output/backtest/<時間>_notebook_04_tuning/`（逐窗分數、逐日 6 目標、432 點曲線 `curves.csv`，供 05 讀取）、`output/reports/04_runtimes.json` |

**現行模型**：
- 時刻（佔總分約 93%）：條件經驗分布（日別 × 夏月 × 星期 × 氣溫 2 箱）+ 學習式 LightGBM 在 PMF 層級修正 + 貝氏決策
- 量值：LightGBM 分位數迴歸（τ = 0.625 / 0.70 / 0.50）
- 氣象：五都 4 個溫度項；歷史用 CODiS 觀測，目標日用逐起點校正的 Accuweather
- 太陽光電：Windy 預測發電量 `pv_14`、`pv_sum`
- 6 目標 → 合成 432 點曲線

**回測設計**（`src/evaluation/backtest.py`）：每個窗從起點日 T 的次日 00:00 起算，負載截止於 T 23:50，
預測 3 天共 432 期；目標日的氣象只用預報（honest 模式）。調參組 = 現有 60 折 + 2025 年 9/19–10/9 每天起算的同季節窗，共 78 窗。
保留確認組（2026 年 7–9 月）只在選定最終設定後使用一次，本 notebook 不會去跑它。

observed 模式（目標日也用觀測，樂觀）只作對照，可由 `python main.py evaluate --weather-mode observed` 重現。

調參組回測約 15 分鐘。

In [1]:
import sys
from pathlib import Path

ROOT = Path.cwd().resolve()
while not (ROOT / "config").is_dir():   # 找到專案根目錄（notebook 可從任何位置執行）
    ROOT = ROOT.parent
sys.path.insert(0, str(ROOT))

import os
import polars as pl
from src.logging_setup import setup_logging

os.chdir(ROOT)
setup_logging(stage="notebook_04", level="WARNING")
pl.Config.set_tbl_rows(60)
pl.Config.set_tbl_cols(30)
pl.Config.set_fmt_str_lengths(60)

polars.config.Config

In [2]:
import datetime as dt
import json
import time

from config import paths, settings
from src import workflow
from src.data import checks
from src.evaluation import backtest

runtimes = {}

## 1. 調參組回測（78 窗）

In [3]:
start = time.perf_counter()
run_dir = backtest.run("tuning", "notebook_04")
runtimes["backtest_tuning"] = round(time.perf_counter() - start, 1)
summary = json.loads((run_dir / "summary.json").read_text(encoding="utf-8"))
paths.REPORTS_DIR.mkdir(parents=True, exist_ok=True)
{k: summary[k] for k in ("n_windows", "skipped", "manifest_sha256", "data_matches_manifest", "runtime_seconds")}

2026-09-29 13:29:30 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:29:31 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:29:33 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:29:38 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:29:40 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:29:42 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:29:47 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:29:49 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:29:51 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:29:56 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:29:58 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:30:00 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:30:05 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:30:07 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:30:09 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:30:14 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:30:16 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:30:18 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:30:23 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:30:25 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:30:27 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:30:33 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:30:35 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:30:37 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:30:43 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:30:45 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:30:47 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:30:52 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:30:54 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:30:56 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:31:02 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:31:04 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:31:06 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:31:12 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:31:14 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:31:16 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:31:21 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:31:24 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:31:26 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:31:31 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:31:34 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:31:36 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:31:42 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:31:44 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:31:46 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:31:52 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:31:54 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:31:56 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:32:02 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:32:04 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:32:06 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:32:12 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:32:14 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:32:17 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:32:23 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:32:25 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:32:27 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:32:33 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:32:35 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:32:38 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:32:44 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:32:46 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:32:48 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:32:55 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:32:57 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:32:59 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:33:05 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:33:08 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:33:10 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:33:16 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:33:18 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:33:21 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:33:27 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:33:29 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:33:32 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:33:38 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:33:40 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:33:43 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:33:49 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:33:51 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:33:54 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:34:00 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:34:03 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:34:05 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:34:12 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:34:14 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:34:16 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:34:23 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:34:25 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:34:27 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:34:34 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:34:37 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:34:39 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:34:46 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:34:48 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:34:50 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:34:57 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:35:00 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:35:02 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:35:09 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:35:11 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:35:13 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:35:20 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:35:22 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:35:24 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:35:31 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:35:34 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:35:36 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:35:43 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:35:45 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:35:47 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:35:54 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:35:56 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:35:59 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:36:05 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:36:08 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:36:10 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:36:17 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:36:19 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:36:21 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:36:28 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:36:31 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:36:33 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:36:40 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:36:42 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:36:44 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:36:51 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:36:53 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:36:56 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:37:03 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:37:05 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:37:07 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:37:14 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:37:16 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:37:19 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:37:25 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:37:28 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:37:30 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:37:37 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:37:39 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:37:42 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:37:49 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:37:51 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:37:53 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:38:00 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:38:02 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:38:05 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:38:12 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:38:14 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:38:16 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:38:23 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:38:25 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:38:27 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:38:35 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:38:37 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:38:39 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:38:47 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:38:49 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:38:51 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:38:59 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:39:01 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:39:04 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:39:11 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:39:13 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:39:16 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:39:23 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:39:26 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:39:28 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:39:36 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:39:38 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:39:40 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:39:48 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:39:51 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:39:53 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:40:01 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:40:03 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:40:06 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:40:14 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:40:16 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:40:18 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:40:26 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:40:29 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:40:31 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:40:39 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:40:42 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:40:44 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:40:52 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:40:55 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:40:57 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:41:05 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:41:08 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:41:10 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:41:18 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:41:21 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:41:23 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:41:32 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:41:34 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:41:37 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:41:45 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:41:48 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:41:50 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:41:59 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:42:01 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:42:03 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:42:12 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:42:14 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:42:17 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:42:26 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:42:28 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:42:30 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:42:39 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:42:42 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:42:44 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:42:53 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:42:55 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:42:58 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:43:07 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:43:10 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:43:12 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:43:21 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:43:24 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:43:26 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:43:36 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:43:38 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:43:40 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:43:50 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:43:52 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:43:55 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:44:04 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:44:06 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:44:09 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:44:18 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:44:21 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:44:23 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:44:33 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:44:35 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:44:37 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:44:40 | WARNING  | src.workflow | total_score = 1.04169（標準誤 0.06788），最壞折 2.77256（2025-08-01）［氣象模式 honest］
shape: (5, 5)
┌─────────────────┬──────────┬────────┬──────────────┬──────────┐
│ component       ┆ raw      ┆ weight ┆ contribution ┆ share    │
│ ---             ┆ ---      ┆ ---    ┆ ---          ┆ ---      │
│ str             ┆ f64      ┆ f64    ┆ f64          ┆ f64      │
╞═════════════════╪══════════╪════════╪══════════════╪══════════╡
│ s_peak_time     ┆ 6.487846 ┆ 0.15   ┆ 0.973177     ┆ 0.934226 │
│ s_ramp_up       ┆ 0.173534 ┆ 0.15   ┆ 0.02603      ┆ 0.024988 │
│ s_ramp_down     ┆ 0.148411 ┆ 0.1    ┆ 0.014841     ┆ 0.014247 │
│ s_peak_mw       ┆ 0.024205 ┆ 0.6    ┆ 0.014523     ┆ 0.013942 │
│ s_under_penalty ┆ 0.013122 ┆ 1.0    ┆ 0.013122     ┆ 0.012597 │
└─────────────────┴──────────┴────────┴──────────────┴──────────┘

2026-09-29 13:44:40 | WARNING  | src.evaluation.backtest | 回測 [notebook_04／tuning] 78 窗：total_score 1.04169（標準誤 0.06788），同季節 0.76025 → 20260929_132929_notebook_04_tuning

{'n_windows': 78,
 'skipped': [],
 'manifest_sha256': 'ecda90d93d378091edd4cbb09e7f42fca63a2a97447c50045a3fa47b6466ab49',
 'data_matches_manifest': True,
 'runtime_seconds': 914.7}

In [4]:
pl.DataFrame([{"範圍": "全體", **summary["overall"]}]
             + [{"範圍": name, **value} for name, value in summary["subsets"].items()])

shape: (6, 11)
┌─────────┬─────┬─────────┬─────────┬────────┬────────┬────────┬────────┬────────┬────────┬────────┐
│ 範圍    ┆ n   ┆ total_s ┆ stderr  ┆ worst  ┆ worst_ ┆ s_peak ┆ s_peak ┆ s_ramp ┆ s_ramp ┆ s_unde │
│ ---     ┆ --- ┆ core    ┆ ---     ┆ ---    ┆ origin ┆ _mw    ┆ _time  ┆ _up    ┆ _down  ┆ r_pena │
│ str     ┆ i64 ┆ ---     ┆ f64     ┆ f64    ┆ ---    ┆ ---    ┆ ---    ┆ ---    ┆ ---    ┆ lty    │
│         ┆     ┆ f64     ┆         ┆        ┆ str    ┆ f64    ┆ f64    ┆ f64    ┆ f64    ┆ ---    │
│         ┆     ┆         ┆         ┆        ┆        ┆        ┆        ┆        ┆        ┆ f64    │
╞═════════╪═════╪═════════╪═════════╪════════╪════════╪════════╪════════╪════════╪════════╪════════╡
│ 全體    ┆ 78  ┆ 1.04169 ┆ 0.06788 ┆ 2.7725 ┆ 2025-0 ┆ 0.0242 ┆ 6.4878 ┆ 0.1735 ┆ 0.1484 ┆ 0.0131 │
│         ┆     ┆ 3       ┆         ┆ 56     ┆ 8-01   ┆ 05     ┆ 46     ┆ 34     ┆ 11     ┆ 22     │
│ 同季節  ┆ 21  ┆ 0.76024 ┆ 0.09280 ┆ 1.8341 ┆ 2025-0 ┆ 0.0247 ┆ 4.6426 ┆ 0.1775 ┆ 0.1497 ┆ 0.0073 │
│         ┆     ┆ 6       ┆ 8       ┆ 23     ┆ 9-20   ┆ 8      ┆ 09     ┆ 68     ┆ 05     ┆ 81     │
│ 週四五  ┆ 11  ┆ 1.18582 ┆ 0.22502 ┆ 2.4145 ┆ 2025-0 ┆ 0.0215 ┆ 7.5007 ┆ 0.1627 ┆ 0.1375 ┆ 0.0096 │
│ 六      ┆     ┆ 7       ┆ 1       ┆ 55     ┆ 6-11   ┆ 75     ┆ 19     ┆ 16     ┆ 15     ┆ 15     │
│ 含週六  ┆ 35  ┆ 1.04930 ┆ 0.11198 ┆ 2.7725 ┆ 2025-0 ┆ 0.0207 ┆ 6.5265 ┆ 0.1958 ┆ 0.1645 ┆ 0.0120 │
│         ┆     ┆ 8       ┆ 2       ┆ 56     ┆ 8-01   ┆ 97     ┆ 01     ┆ 66     ┆ 91     ┆ 16     │
│ 夏月末  ┆ 18  ┆ 0.62221 ┆ 0.05931 ┆ 1.0272 ┆ 2025-0 ┆ 0.0227 ┆ 3.7072 ┆ 0.1964 ┆ 0.1639 ┆ 0.0065 │
│ 期      ┆     ┆ 3       ┆ 5       ┆ 1      ┆ 9-27   ┆ 99     ┆ 44     ┆ 15     ┆ 04     ┆ 94     │
│ 含連假  ┆ 27  ┆ 1.03328 ┆ 0.09509 ┆ 1.9080 ┆ 2026-0 ┆ 0.0276 ┆ 6.3480 ┆ 0.2504 ┆ 0.1825 ┆ 0.0086 │
│ 或停班  ┆     ┆ 5       ┆ 8       ┆ 72     ┆ 4-04   ┆ 06     ┆ 33     ┆ 77     ┆ 42     ┆ 91     │
└─────────┴─────┴─────────┴─────────┴────────┴────────┴────────┴────────┴────────┴────────┴────────┘

## 2. 以鎖定設定重新訓練並預測（開發期：截止日次日起 3 天）

與比賽當天 `run_submission.py` 第 5–6 步是同一個函式。

In [5]:
origin = checks.cutoff_date()
days = [origin + dt.timedelta(days=k) for k in range(1, settings.PREDICT_HORIZON_DAYS + 1)]
start = time.perf_counter()
curves, intended = workflow.predict_days(origin, days)
runtimes["train_and_predict"] = round(time.perf_counter() - start, 1)
pl.DataFrame([
    {"日期": str(day), "p_day": t.p_day, "t_day": t.t_day, "p_night": t.p_night,
     "t_night": t.t_night, "ramp_up": t.ramp_up, "ramp_down": t.ramp_down}
    for day, t in intended.items()
])

2026-09-29 13:44:41 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:44:42 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:44:43 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:44:44 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:44:53 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:44:55 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

2026-09-29 13:44:57 | WARNING  | src.data.checks | Windy：完全重複 122 列，已刪除

shape: (3, 7)
┌────────────┬──────────────┬───────┬──────────────┬─────────┬─────────────┬────────────┐
│ 日期       ┆ p_day        ┆ t_day ┆ p_night      ┆ t_night ┆ ramp_up     ┆ ramp_down  │
│ ---        ┆ ---          ┆ ---   ┆ ---          ┆ ---     ┆ ---         ┆ ---        │
│ str        ┆ f64          ┆ i64   ┆ f64          ┆ i64     ┆ f64         ┆ f64        │
╞════════════╪══════════════╪═══════╪══════════════╪═════════╪═════════════╪════════════╡
│ 2026-07-01 ┆ 39766.857637 ┆ 840   ┆ 36729.72771  ┆ 1030    ┆ 1426.894147 ┆ 716.383084 │
│ 2026-07-02 ┆ 39905.866259 ┆ 840   ┆ 36456.997301 ┆ 1030    ┆ 1482.205991 ┆ 693.389594 │
│ 2026-07-03 ┆ 39491.71789  ┆ 840   ┆ 36574.059603 ┆ 1030    ┆ 1463.318588 ┆ 672.770172 │
└────────────┴──────────────┴───────┴──────────────┴─────────┴─────────────┴────────────┘

In [6]:
(paths.REPORTS_DIR / "04_runtimes.json").write_text(json.dumps(runtimes, indent=2), encoding="utf-8")
runtimes

{'backtest_tuning': 914.7, 'train_and_predict': 20.0}

## 3. 實驗總表

每個實驗都走同一套回測（調參組 78 窗、honest 模式），與當時的參考配對比較。
**所有變體都在執行前決定**，看到結果後沒有追加或微調，以免對調參組過度配適。

選模門檻：全部調參窗的配對改善大於 1 個標準誤，且同季節子集沒有變差超過 1 個標準誤；
通過者再以另外 2 個種子確認。差值為正代表變差；「對照」是配對比較的參考紀錄。

In [7]:
EXPERIMENTS = {
    "current_best": "參考：含 UV、不含 Windy",
    "codis_lag1": "CODiS 只到起點前一天",
    "4a_A1_noUV": "氣象不含 UV（採用）",
    "4a_A1raw_noUV_uncal": "目標日預報不校正",
    "4a_B_forecast": "歷史也改用預報",
    "4a_N_noweather": "不用氣象",
    "4c_windy": "加入 Windy 太陽光電預測（採用）",
    "4e_E1_timing_seeds5": "時刻學習模型 5 種子平均",
    "4f_drop_zero_split": "刪除 6 個未使用的特徵（採用）",
    "4g_mix03": "時刻學習權重 0.3",
    "4g_mix07": "時刻學習權重 0.7",
    "4h_magnitude_seeds5": "量值模型 5 種子平均",
    "4d_recursive_ar": "對照：10 分鐘一步的遞迴 AR",
}
names = pl.DataFrame({"label": list(EXPERIMENTS), "實驗": list(EXPERIMENTS.values())})
experiments = names.join(backtest.experiment_table("2026*"), on="label", how="left")
experiments.select("實驗", "total_score", "同季節", "s_peak_time", "差值", "標準誤倍數",
                   "同季節差值", "通過門檻", "對照", "耗時秒")

shape: (13, 10)
┌─────────┬─────────┬─────────┬─────────┬─────────┬─────────┬─────────┬─────────┬─────────┬────────┐
│ 實驗    ┆ total_s ┆ 同季節  ┆ s_peak_ ┆ 差值    ┆ 標準誤  ┆ 同季節  ┆ 通過門  ┆ 對照    ┆ 耗時秒 │
│ ---     ┆ core    ┆ ---     ┆ time    ┆ ---     ┆ 倍數    ┆ 差值    ┆ 檻      ┆ ---     ┆ ---    │
│ str     ┆ ---     ┆ f64     ┆ ---     ┆ f64     ┆ ---     ┆ ---     ┆ ---     ┆ str     ┆ f64    │
│         ┆ f64     ┆         ┆ f64     ┆         ┆ f64     ┆ f64     ┆ bool    ┆         ┆        │
╞═════════╪═════════╪═════════╪═════════╪═════════╪═════════╪═════════╪═════════╪═════════╪════════╡
│ 參考：  ┆ 1.05629 ┆ 0.75880 ┆ 6.58006 ┆ null    ┆ null    ┆ null    ┆ null    ┆ null    ┆ 912.1  │
│ 含 UV、 ┆ 4       ┆ 8       ┆ 9       ┆         ┆         ┆         ┆         ┆         ┆        │
│ 不含    ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ Windy   ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ CODiS   ┆ 1.05935 ┆ 0.75971 ┆ 6.60064 ┆ 0.00306 ┆ 0.67262 ┆ 0.00090 ┆ false   ┆ 2026092 ┆ 1482.0 │
│ 只到起  ┆ 7       ┆ 7       ┆ 1       ┆ 3       ┆ 9       ┆ 9       ┆         ┆ 7_14200 ┆        │
│ 點前一  ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆ 0_curre ┆        │
│ 天      ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆ nt_best ┆        │
│         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆ _tuning ┆        │
│ 氣象不  ┆ 1.06447 ┆ 0.76073 ┆ 6.62996 ┆ 0.00818 ┆ 0.80785 ┆ 0.00193 ┆ false   ┆ 2026092 ┆ 1919.0 │
│ 含 UV（ ┆ 5       ┆ 8       ┆ 8       ┆ 1       ┆ 5       ┆         ┆         ┆ 7_14200 ┆        │
│ 採用）  ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆ 0_curre ┆        │
│         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆ nt_best ┆        │
│         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆ _tuning ┆        │
│ 目標日  ┆ 1.08094 ┆ 0.77772 ┆ 6.74490 ┆ 0.02465 ┆ 1.93774 ┆ 0.01891 ┆ false   ┆ 2026092 ┆ 1975.8 │
│ 預報不  ┆ 9       ┆ 2       ┆ 1       ┆ 5       ┆ 6       ┆ 4       ┆         ┆ 7_14200 ┆        │
│ 校正    ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆ 0_curre ┆        │
│         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆ nt_best ┆        │
│         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆ _tuning ┆        │
│ 歷史也  ┆ 1.07602 ┆ 0.76911 ┆ 6.71522 ┆ 0.01973 ┆ 1.58086 ┆ 0.01030 ┆ false   ┆ 2026092 ┆ 2793.4 │
│ 改用預  ┆ 9       ┆ 4       ┆ 1       ┆ 5       ┆ 4       ┆ 6       ┆         ┆ 7_14200 ┆        │
│ 報      ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆ 0_curre ┆        │
│         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆ nt_best ┆        │
│         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆ _tuning ┆        │
│ 不用氣  ┆ 1.08729 ┆ 0.79947 ┆ 6.77339 ┆ 0.03100 ┆ 1.91130 ┆ 0.04066 ┆ false   ┆ 2026092 ┆ 1852.5 │
│ 象      ┆ 5       ┆ 7       ┆ 2       ┆ 2       ┆ 1       ┆ 9       ┆         ┆ 7_14200 ┆        │
│         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆ 0_curre ┆        │
│         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆ nt_best ┆        │
│         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆ _tuning ┆        │
│ 加入    ┆ 1.04169 ┆ 0.76024 ┆ 6.48784 ┆ -0.0227 ┆ 1.81051 ┆ -0.0004 ┆ true    ┆ 2026092 ┆ 2097.8 │
│ Windy   ┆ 3       ┆ 6       ┆ 6       ┆ 81      ┆ 1       ┆ 91      ┆         ┆ 8_10130 ┆        │
│ 太陽光  ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆ 0_4a_A1 ┆        │
│ 電預測  ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆ _noUV_t ┆        │
│ （採用  ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆ uning   ┆        │
│ ）      ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ 時刻學  ┆ 1.05931 ┆ 0.77352 ┆ 6.60019 ┆ 0.00301 ┆ 0.62047 ┆ 0.01472 ┆ false   ┆ 2026092 ┆ 4314.5 │
│ 習模型  ┆ 2       ┆ 9       ┆         ┆ 8       ┆ 6       ┆ 1       ┆         ┆ 7_14200 ┆        │
│ 5 種子  ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆ 0_curre ┆        │
│ 平均    ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆ nt_best ┆        │
│         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆ _tuning ┆        │
│ 刪除 6  ┆ 1.06447 ┆ 0.76073 ┆ 6.62996 ┆ 0.0     ┆ inf     ┆ 0.0     ┆ false   ┆ 2026092 ┆ 2097.1 │
│ 個未使  ┆ 5       ┆ 8       ┆ 8       ┆         ┆         ┆         ┆         ┆ 8_10130 ┆        │
│ 用的特  ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆ 0_4a_A1 ┆        │
│ 徵（採  ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆ _noUV_t ┆        │
│ 用）    ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆ uning   ┆        │
│ 時刻學  ┆ 1.07946 ┆ 0.82645 ┆ 6.72975 ┆ 0.01498 ┆ 1.18992 ┆ 0.06572 ┆ false   ┆ 2026092 ┆ 2399.9 │
│ 習權重  ┆         ┆ 8       ┆         ┆ 5       ┆ 6       ┆ 1       ┆         ┆ 8_10130 ┆        │
│ 0.3     ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆ 0_4a_A1 ┆        │
│         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆ _noUV_t ┆        │
│         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆ uning   ┆        │
│ 時刻學  ┆ 1.06094 ┆ 0.70632 ┆ 6.60642 ┆ -0.0035 ┆ 0.22482 ┆ -0.0544 ┆ false   ┆ 2026092 ┆ 2391.9 │
│ 習權重  ┆ 3       ┆ 5       ┆ 2       ┆ 32      ┆ 4       ┆ 12      ┆         ┆ 8_10130 ┆        │
│ 0.7     ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆ 0_4a_A1 ┆        │
│         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆ _noUV_t ┆        │
│         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆ uning   ┆        │
│ 量值模  ┆ 1.06388 ┆ 0.75936 ┆ 6.62996 ┆ -0.0005 ┆ 1.52613 ┆ -0.0013 ┆ true    ┆ 2026092 ┆ 5095.2 │
│ 型 5    ┆ 4       ┆ 9       ┆ 8       ┆ 9       ┆ 6       ┆ 69      ┆         ┆ 8_10130 ┆        │
│ 種子平  ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆ 0_4a_A1 ┆        │
│ 均      ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆ _noUV_t ┆        │
│         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆ uning   ┆        │
│ 對照：1 ┆ 1.90909 ┆ 0.88830 ┆ 11.6666 ┆ 0.84462 ┆ 7.75091 ┆ 0.12757 ┆ false   ┆ 2026092 ┆ 37.0   │
│ 0 分鐘  ┆ 4       ┆ 9       ┆ 61      ┆         ┆ 2       ┆ 2       ┆         ┆ 8_10130 ┆        │
│ 一步的  ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆ 0_4a_A1 ┆        │
│ 遞迴 AR ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆ _noUV_t ┆        │
│         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆ uning   ┆        │
└─────────┴─────────┴─────────┴─────────┴─────────┴─────────┴─────────┴─────────┴─────────┴────────┘

In [8]:
experiments.select("實驗", "label", "覆寫")

shape: (13, 3)
┌─────────────────────────────────┬─────────────────────┬──────────────────────────────────────────┐
│ 實驗                            ┆ label               ┆ 覆寫                                     │
│ ---                             ┆ ---                 ┆ ---                                      │
│ str                             ┆ str                 ┆ str                                      │
╞═════════════════════════════════╪═════════════════════╪══════════════════════════════════════════╡
│ 參考：含 UV、不含 Windy         ┆ current_best        ┆ {}                                       │
│ CODiS 只到起點前一天            ┆ codis_lag1          ┆ {}                                       │
│ 氣象不含 UV（採用）             ┆ 4a_A1_noUV          ┆ {"WEATHER_METRICS": ["day_tmax",         │
│                                 ┆                     ┆ "day_tmin", "night_tmax", "…             │
│ 目標日預報不校正                ┆ 4a_A1raw_noUV_uncal ┆ {"WEATHER_METRICS": ["day_tmax",         │
│                                 ┆                     ┆ "day_tmin", "night_tmax", "…             │
│ 歷史也改用預報                  ┆ 4a_B_forecast       ┆ {}                                       │
│ 不用氣象                        ┆ 4a_N_noweather      ┆ {"ENABLE_TIER1_WEATHER": false,          │
│                                 ┆                     ┆ "TIMING_TEMPERATURE_BINS": 1…            │
│ 加入 Windy 太陽光電預測（採用） ┆ 4c_windy            ┆ {"ENABLE_WINDY": true}                   │
│ 時刻學習模型 5 種子平均         ┆ 4e_E1_timing_seeds5 ┆ {"TIMING_LEARNED_N_SEEDS": 5}            │
│ 刪除 6 個未使用的特徵（採用）   ┆ 4f_drop_zero_split  ┆ {"EXCLUDED_FEATURES":                    │
│                                 ┆                     ┆ ["is_lunar_new_year_eve", "night_price…  │
│ 時刻學習權重 0.3                ┆ 4g_mix03            ┆ {"TIMING_LEARNED_MIX": 0.3}              │
│ 時刻學習權重 0.7                ┆ 4g_mix07            ┆ {"TIMING_LEARNED_MIX": 0.7}              │
│ 量值模型 5 種子平均             ┆ 4h_magnitude_seeds5 ┆ {"MAGNITUDE_N_SEEDS": 5}                 │
│ 對照：10 分鐘一步的遞迴 AR      ┆ 4d_recursive_ar     ┆ {"MODEL_VARIANT": "recursive_ar"}        │
└─────────────────────────────────┴─────────────────────┴──────────────────────────────────────────┘